# Generated by Django 2.2.6 on 2019-11-03 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='lift',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifts.Movement'),
        ),
    ]
