# Generated by Django 2.2.6 on 2019-11-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0006_lift_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='reps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reps'),
        ),
        migrations.AddField(
            model_name='lift',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight Lifted'),
        ),
    ]
