# Generated by Django 4.0.4 on 2022-04-30 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Lift Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "one_rep_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="One Rep Max"
                    ),
                ),
                (
                    "fake_one_rep",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Theoretical One Rep"
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Weight Lifted"
                    ),
                ),
                (
                    "reps",
                    models.IntegerField(blank=True, null=True, verbose_name="Reps"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Set"),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whiteboard.movement",
                        to_field="name",
                        verbose_name="Lift Name",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
