# Generated by Django 2.2.6 on 2019-11-09 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whiteboard", "0004_auto_20191108_0612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lift",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="whiteboard.Movement",
                to_field="name",
                verbose_name="Lift Name",
            ),
        ),
    ]
