# Generated by Django 2.2.6 on 2019-11-17 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("whiteboard", "0007_auto_20191112_0152"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Exercise Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WodType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="WOD Type"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WOD",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="WOD Name"
                    ),
                ),
                ("rounds", models.IntegerField(default=1)),
                (
                    "rep_score",
                    models.IntegerField(blank=True, null=True, verbose_name="Score"),
                ),
                (
                    "time_score",
                    models.DurationField(blank=True, null=True, verbose_name="Score"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Set"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "wod_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whiteboard.WodType",
                        to_field="name",
                        verbose_name="WOD Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepScheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reps", models.IntegerField(verbose_name="Reps")),
                (
                    "weight",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Weight Lifted"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whiteboard.Exercise",
                        to_field="name",
                        verbose_name="Exercise Name",
                    ),
                ),
                (
                    "wod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whiteboard.WOD",
                        to_field="name",
                        verbose_name="WOD Name",
                    ),
                ),
            ],
        ),
    ]
