# Generated by Django 2.2.6 on 2020-01-25 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("whiteboard", "0008_exercise_repscheme_wod_wodtype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repscheme",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="rep_score",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="time_score",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="user",
        ),
        migrations.AlterField(
            model_name="repscheme",
            name="wod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="whiteboard.WOD",
                verbose_name="WOD Name",
            ),
        ),
        migrations.CreateModel(
            name="WodScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rep_score",
                    models.IntegerField(blank=True, null=True, verbose_name="Score"),
                ),
                (
                    "time_score",
                    models.DurationField(blank=True, null=True, verbose_name="Score"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Set"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "wod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whiteboard.WOD",
                        to_field="name",
                        verbose_name="WOD Name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepWeight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField(verbose_name="Weight")),
                (
                    "rep_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whiteboard.RepScheme",
                        verbose_name="Rep Scheme",
                    ),
                ),
            ],
        ),
    ]
