# Generated by Django 2.2.13 on 2021-02-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whiteboard", "0009_auto_20200125_2224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repscheme",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="repscheme",
            name="wod",
        ),
        migrations.RemoveField(
            model_name="repweight",
            name="rep_scheme",
        ),
        migrations.RemoveField(
            model_name="wod",
            name="wod_type",
        ),
        migrations.RemoveField(
            model_name="wodscore",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wodscore",
            name="wod",
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="RepScheme",
        ),
        migrations.DeleteModel(
            name="RepWeight",
        ),
        migrations.DeleteModel(
            name="WOD",
        ),
        migrations.DeleteModel(
            name="WodScore",
        ),
        migrations.DeleteModel(
            name="WodType",
        ),
    ]
